apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-data-logger-deploy
  namespace: app-prod
  labels:
    app: sensor-data-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-data-logger
  template:
    metadata:
      labels:
        app: sensor-data-logger
    spec:
      containers:
        - name: sensor-data-collector
          image: registry.ruchan.dev/iot/prod/sensor-data-logger:250611-5115803
          envFrom:
            - secretRef:
                name: postgres-secret
          securityContext:
            privileged: true
      imagePullSecrets:
        - name: registry-credentials
