name: Docker Image CI - Dev

on:
  push:
    branches:
      - dev

  workflow_dispatch:

# given github push permissions for github actions

permissions:
  contents: write 

jobs:


  build-data-logger:
    if: |
        startsWith(github.event.head_commit.message, 'build-all') ||
        startsWith(github.event.head_commit.message, 'logger') 

    runs-on: ubuntu-24.04-arm

    env:
      IMAGE_NAME: registry.ruchan.dev/iot/prod/sensor-data-logger

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          registry: registry.ruchan.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set IMAGE_TAG
        run: |
          IMAGE_TAG=$(date +%y%m%d)-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
      - name: Build Docker Image
        run: |
          docker build -f sensor-data-logger/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG sensor-data-logger

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

  build-data-sender:
      if: |
        startsWith(github.event.head_commit.message, 'build-all') ||
        startsWith(github.event.head_commit.message, 'sender') 
      runs-on: ubuntu-24.04-arm

      env:
        IMAGE_NAME: registry.ruchan.dev/iot/prod/sensor-data-logger

      steps:
            
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: docker login
          uses: docker/login-action@v3.4.0
          with:
            registry: registry.ruchan.dev
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Set IMAGE_TAG
          run: |
            IMAGE_TAG=$(date +%y%m%d)-$(git rev-parse --short HEAD)
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
            
        - name: Build Docker Image
          run: |
            docker build -f sensor-data-logger/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG sensor-data-sender

        - name: Push Docker Image
          run: |
            docker push $IMAGE_NAME:$IMAGE_TAG

  update-infra-data-logger:
    needs: build-data-logger
    runs-on: ubuntu-24.04

    env:
      IMAGE_NAME: registry.ruchan.dev/iot/prod/sensor-data-logger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      
      - name: Set IMAGE_TAG again
        run: |
          IMAGE_TAG=$(date +%y%m%d)-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Change Deployment Image Tag
        run: |          
          yq e '.spec.template.spec.containers[0].image = "'$IMAGE_NAME':'$IMAGE_TAG'"' -i k8s-infra/IOT/sensor-data-logger/deployment.yaml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull
          git add k8s-infra/IOT/sensor-data-logger/

          if git diff --staged --quiet; then
            echo "No changes to commit, skipping push."
          else
            git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
            git push
          fi

  update-infra-data-sender:
    needs: build-data-sender
    runs-on: ubuntu-24.04

    env:
      IMAGE_NAME: registry.ruchan.dev/iot/prod/sensor-data-sender

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      
      - name: Set IMAGE_TAG again
        run: |
          IMAGE_TAG=$(date +%y%m%d)-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Change Deployment Image Tag
        run: |          
          yq e '.spec.template.spec.containers[0].image = "'$IMAGE_NAME':'$IMAGE_TAG'"' -i k8s-infra/IOT/sensor-data-sender/deployment.yaml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s-infra/IOT/sensor-data-sender/
          git pull
          
          if git diff --staged --quiet; then
            echo "No changes to commit, skipping push."
          else
            git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
            git push
          fi