name: Docker Image CI

on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
      
    # Pythnon unit tests will be added here

  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rchyln/iot/prod/sensor-data-logger

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set IMAGE_TAG
        run: |
          IMAGE_TAG=$(date +%y%m%d)-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
      - name: Build Docker Image
        run: |
          docker build -f sensor-data-logger/basic/Dockerfile -t rchyln/iot/prod/sensor-data-logger:$IMAGE_TAG sensor-data-logger/basic 

      - name: Push Docker Image
        run: |
          docker push rchyln/iot/prod/sensor-data-logger:$IMAGE_TAG

  update-infra:
    needs: build
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rchyln/IOT/prod/sensor-data-logger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      
      - name: Set IMAGE_TAG again
        run: |
          IMAGE_TAG=$(date +%y%m%d)-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Change Deployment Image Tag
        run: |          
          yq e '.spec.template.spec.containers[0].image = "'$IMAGE_NAME':'$IMAGE_TAG'"' -i k8s-infra/sensor-data-logger/deployment.yaml